export default {
  user: {
    id: 3,
    email: 'user@user.com',
    roles: ['ROLE_USER'],
    firstname: 'Jeff',
    lastname: 'Lebowski',
    nickname: 'El_Dude',
    avatar:
      'https://back-apotheose.eco-friendly.fr/assets/img/avatars/ours.png',
    is_active: true,
    is_verified: true,
    created_at: {
      date: '2023-03-11 17:52:55.000000',
      timezone_type: 3,
      timezone: 'UTC',
    },
    updated_at: {
      date: '2023-03-19 18:59:16.000000',
      timezone_type: 3,
      timezone: 'UTC',
    },
  },
  token:
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NzkyNjA3NzIsImV4cCI6MTY3OTI2NDM3Miwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidXNlckB1c2VyLmNvbSJ9.ZEmbnRw8WYJvpfNPoESZEe7q5O5tfvYz6ZLT2HCavNFjSqGaaZNRYoK4mySKyrpIdvp_phb4OkTHzvGzmOmlavl0u4H8DChTzj4c1E_Sa3KX4qyTzEKrVBmui_TRypmJXbUuQUI_ZtxBiBHGPSVuPszovFzB0xZ8k3wJluyFAbLxwC-sc5FB1UipbKWoh3RA5GBRtAldu8-qNurhC0JDe3cj_c8qqNebVsoK5HyO7YmjHYhDrF5Dsx4VA-3SQaZnMhoZMac0Tp001Uhewgha2t8fd9oZvvkRU8NgN06JSkhCIYisxK1sd3Ds4tTQK2Me88Hm8JL9afJJEmMr0N88pw',
  categories: [
    {
      id: 1,
      name: 'Mobilité',
      slug: 'mobilite',
      tagline: 'Eaque enim enim quaerat est velit qui quia.',
    },
    {
      id: 2,
      name: 'Maison',
      tagline: 'Eveniet quis reiciendis cum.',
      slug: 'maison',
    },
    {
      id: 3,
      name: 'Santé',
      tagline:
        'Dolores corporis ullam libero exercitationem corporis adipisci quo et.',
      slug: 'sante',
    },
    {
      id: 4,
      name: 'Energie',
      tagline: 'Nisi modi ducimus laborum autem.',
      slug: 'energie',
    },
  ],
  articles: {
    home: [
      {
        id: 106,
        title: 'Cum minima porro et illum.',
        content:
          '<p>Lorem ipsum dolor sit amet. Vel dolorem eligendiest unde aut recusandae dolores. Ut earum architecto <a href="https://www.loremipzum.com" target="_blank">Non libero eos recusandae maxime a architecto delectus qui earum ipsum</a> est voluptas dolor est numquam adipisci. 33 voluptas magnam <em>Ab animi quo eaque aliquid</em>.</p>\r\n\r\n<ol>\r\n\t<li>Ut odio officiis sed nihil rerum et sint pariatur.</li>\r\n\t<li>Aut dolore laborum eum architecto recusandae a laudantium nobis aut nulla quia.</li>\r\n\t<li>Sit animi enim qui sunt magnam in nihil possimus.</li>\r\n\t<li>Rem possimus numquam ex quaerat rerum.</li>\r\n</ol>\r\n\r\n<ul>\r\n\t<li>Eum commodi galisum eos quam voluptate qui porro asperiores ut consequatur quia.</li>\r\n\t<li>Est voluptatum perspiciatis vel nulla voluptas ea sunt modi ab quos vero.</li>\r\n\t<li>Et dolor cupiditate ut quae enim aut internos nulla est saepe quod?</li>\r\n\t<li>Cum alias minus At fuga dolor.</li>\r\n\t<li>Est enim veniam aut recusandae tenetur eum similique natus.</li>\r\n\t<li>Hic veritatis excepturi 33 velit consequuntur sit quidem molestiae.</li>\r\n</ul>\r\n\r\n<h2>Aut beatae sint et porro perferendis est reiciendis excepturi.</h2>\r\n\r\n<p>At itaque atque ut esse iste <a href="https://www.loremipzum.com" target="_blank">Et praesentium ea culpa atque aut esse dolorem qui maxime exercitationem</a>. 33 quibusdam molestias cum voluptatem totam <em>Ea quae non tempora minus et laborum dicta ut cupiditate tempora</em>.</p>\r\n\r\n<blockquote>Est autem tenetur sed optio illum ad atque earum quo repudiandae neque aut dolor nostrum est dolores exercitationem.</blockquote>\r\n\r\n<h3>Et dolore sint aut rerum ipsam.</h3>\r\n\r\n<p>Vel nemo possimus <strong>Eum natus qui doloribus doloremque et omnis necessitatibus sed sequi tenetur</strong> nam porro earum non dolorem dicta! Et aspernatur molestiae ad voluptas cumque <em>Ut quia vel Quis earum nam quidem voluptas</em>. Non aperiam molestiaeaut neque aut atque dolores. Id animi esseEst sequi ut molestias quam et velit porro vel dolor perspiciatis et omnis minus.</p>\r\n\r\n<p>Et nihil quaerat ut incidunt quisquam.</p>\r\n\r\n<p>A itaque aliquid 33 molestiae maxime?</p>\r\n\r\n<p>Id internos adipisci.</p>\r\n\r\n<p>Quo ipsum omnis 33 voluptatem accusantium ut omnis nemo ea magnam facere!</p>\r\n\r\n<p>Est laborum nemo.</p>\r\n\r\n<p>Ex quia error ab tenetur expedita qui aliquam quam.</p>\r\n\r\n<p>A consequatur illum ex molestias eius.</p>\r\n\r\n<p>Ut quaerat enim eum culpa dolores et dolore maxime non dolor architecto!</p>\r\n\r\n<pre>\r\n<code>&lt;!-- In voluptatibus odit. --&gt;\r\n&lt;sed&gt;Ad praesentium dolorum est itaque voluptas?&lt;/sed&gt;\r\n&lt;ipsam&gt;Cum ullam praesentium.&lt;/ipsam&gt;\r\n&lt;nesciunt&gt;Id voluptatibus minus.&lt;/nesciunt&gt;\r\n&lt;et&gt;Sit fugit molestiae.&lt;/et&gt;\r\n</code></pre>',
        slug: 'cum-minima-porro-et-illum',
        picture:
          'https://back-apotheose.eco-friendly.fr/uploads/articles/cum-minima640ef55fef35b.png',
        status: 1,
        created_at: '2023-03-13T10:05:19+00:00',
        updated_at: '2023-03-13T10:05:46+00:00',
        author: {
          id: 60,
          email: 'laure.riglet@protonmail.com',
          roles: ['ROLE_AUTHOR', 'ROLE_USER'],
          firstname: 'Deirdre',
          lastname: 'Chan',
          nickname: 'Martena',
          code: '#9868',
          avatar:
            'https://back-apotheose.eco-friendly.fr/uploads/users/60-640ef51529f0b.jpg',
          is_active: true,
          is_verified: true,
          created_at: '2023-03-13T10:02:17+00:00',
          updated_at: '2023-03-13T10:04:05+00:00',
        },
        category: {
          id: 1,
          name: 'Mobilité',
          tagline: 'Eaque enim enim quaerat est velit qui quia.',
          slug: 'mobilite',
        },
      },
      {
        id: 24,
        title: 'Molestias minima assumenda qui est.',
        content:
          '<p><em>Id ab corrupti quia minima beatae et facilis. Ipsam sed illum culpa iusto maiores sequi. Et qui eos maxime consequuntur quas. Quaerat sed dolorem officia ducimus pariatur. Corporis necessitatibus ea est iure quo enim et. Tenetur qui fugiat cum dolores cumque. Dolore et ut dignissimos sit voluptatem.</em></p><h3>Dolores eligendi ad deserunt ut.</h3><p>Illo quibusdam enim cum quisquam quia temporibus fugit. Quo et facilis dicta omnis nulla. Asperiores in porro consequatur rem ex. Quis voluptatum in modi ex. Ut omnis sapiente non voluptate quae.</p><p><b>Modi iste mollitia et nam aut earum. Laudantium laboriosam quod vel qui ea. Dolor tempore laboriosam vel impedit. Eos cumque sint temporibus. Voluptas et numquam vel quo consectetur et fugit laudantium. Aliquid et rerum nesciunt repellat veniam. Quae optio amet incidunt sed. Inventore excepturi aut est dolor maiores cumque labore. Nam velit omnis excepturi suscipit et.</b></p><p>Rem magnam aut impedit tempora. At aut voluptatem non. Nihil voluptates aliquam nihil aut numquam dolorem iste. Omnis molestias suscipit ea aperiam sit ut. Aperiam explicabo qui et consequatur deleniti officiis et eligendi. Nisi cum neque sequi sit saepe perspiciatis.</p><h4>Vitae quis blanditiis aliquam ipsa aut minus.</h4><ul><li>Nulla aut sed at recusandae.</li><li>Enim exercitationem qui non est iste.</li><li>Impedit est ea repellendus autem ipsam ut aut.</li></ul><h3>Accusantium est sunt similique in facilis.</h3><p>Officiis amet doloribus eligendi qui quod omnis. Qui amet odit quae corrupti cum non. Amet eveniet atque ut perferendis atque eius vel cum. Quo libero eligendi ut eum qui voluptatem provident doloribus. Assumenda totam quo cum ex. Consequatur esse laboriosam autem et reprehenderit officiis quibusdam. Et natus perferendis id temporibus. Soluta commodi vero eos molestias sequi inventore quasi. Praesentium illo exercitationem minima et fugiat.</p><p>Non officia odio cupiditate odit eius molestias omnis recusandae. Soluta impedit ipsum aperiam quasi perferendis ratione. Nihil nisi qui quod quidem quibusdam et iure. Et est beatae accusantium culpa quaerat non sapiente. Quas aperiam minus temporibus voluptatum similique eveniet delectus magni.</p><p>Et minus et reprehenderit voluptatem asperiores. Quia iusto tenetur saepe explicabo. Minus animi minus eum. Id maxime magnam a deleniti. Asperiores et quae minus saepe. Mollitia qui ad explicabo exercitationem aut eum minus. Reprehenderit impedit asperiores accusantium sequi quia. Possimus placeat excepturi autem nemo error nobis. Ut aut consectetur ex est numquam ab deserunt rerum.</p><p><em>Ut excepturi ab quia tempora. Ullam nihil voluptatem beatae tempore ipsa esse. Magni ut suscipit ut unde officia cum. Corporis temporibus ipsam aut quia vel pariatur voluptas. Autem minus asperiores voluptas labore est et. Omnis aut deserunt quo et quos dolorem. Deserunt veniam voluptas aut non omnis quia. Sed eaque et recusandae quo exercitationem. Totam hic consectetur maxime sit sint ipsam perferendis.</em></p>',
        slug: 'molestias-minima-assumenda-qui-est',
        picture: 'https://picsum.photos/id/72/1000/1000.jpg',
        status: 1,
        created_at: '2023-03-12T14:27:22+00:00',
        updated_at: '2022-03-15T07:30:04+00:00',
        author: {
          id: 5,
          email: 'swift.alford@mitchell.info',
          roles: ['ROLE_AUTHOR', 'ROLE_USER'],
          firstname: 'Assunta',
          lastname: 'Mann',
          nickname: 'parisian.arjun',
          code: '#5374',
          avatar:
            'https://back-apotheose.eco-friendly.fr/assets/img/avatars/chevreuil.png',
          is_active: true,
          is_verified: true,
          created_at: '2022-06-29T20:23:16+00:00',
          updated_at: '2022-09-17T00:27:27+00:00',
        },
        category: {
          id: 2,
          name: 'Maison',
          tagline: 'Eveniet quis reiciendis cum.',
          slug: 'maison',
        },
      },
      {
        id: 52,
        title: 'Amet sit commodi et inventore doloremque velit.',
        content:
          '<p><em>Minus ut ipsam quae earum cum qui. Ipsam omnis nostrum cupiditate sunt. Molestiae dicta quidem et voluptates sapiente provident sunt voluptatum. Cumque corrupti voluptate ea asperiores est. Error accusantium ea voluptate beatae natus cum doloremque. Aut rem qui consequatur. Magni deserunt quibusdam sit sint. Maxime alias autem qui dolores.</em></p><h3>Omnis facere reiciendis tenetur quos voluptate nisi earum.</h3><p>Architecto itaque debitis necessitatibus dolorum. Magni tempore aut ut amet. Aut impedit ipsam aspernatur natus ad magni non. Libero adipisci excepturi ut non est explicabo suscipit. Ad culpa qui molestiae. Magni laudantium aliquid quas consequuntur. Deleniti et sed non ut ducimus deleniti. Eum blanditiis est praesentium consequuntur.</p><p><b>Quos earum tempore similique voluptas sunt quo porro. Totam voluptatem facere ut ipsa ipsum qui at. Voluptatem ea nobis accusamus vel molestias. Recusandae alias inventore aut architecto quia. Dolores reprehenderit incidunt consequatur inventore beatae consequatur odit.</b></p><p>Autem aut fugit nemo voluptatem libero commodi. Sit magnam voluptatibus eaque eius iure ut. Expedita et ipsum vitae enim magni ut quaerat. Maxime quae ut cupiditate. Eos est deleniti corporis aspernatur perferendis dolorem. Doloribus deserunt id aliquam iusto fugiat ut.</p><h4>Ut facere est voluptas eveniet quia sequi.</h4><ul><li>In fugiat itaque animi iste.</li><li>A dolor consequatur hic et omnis tempora velit.</li><li>Earum maiores aliquam ut laudantium.</li></ul><h3>Illo voluptatibus nihil sapiente sed et.</h3><p>Exercitationem autem ut quisquam non provident. Assumenda labore nihil non non illum ipsam quia. Illo saepe veritatis id nisi a eius. Doloremque fuga esse autem.</p><p>Molestiae occaecati aut placeat et ducimus. Totam aut animi et placeat deserunt blanditiis laborum. Quisquam ipsa amet pariatur ipsa ducimus aut. Aperiam laborum voluptates aspernatur aut. Dignissimos provident consequuntur est quia. Id veniam quaerat rerum iusto in dicta quod facere. In id possimus ut est laboriosam ut quae.</p><p>Ea beatae iure ut mollitia. Reprehenderit dolore qui sint id earum. Sed et voluptatem rerum ex quia iusto animi. Magnam quia voluptas optio qui perspiciatis id repudiandae. Est et doloribus molestiae accusamus. Quibusdam non deserunt quo dignissimos. Minima nemo voluptate error quod quia dolorem eius. Sint id amet fugiat vel consequuntur culpa ipsam.</p><p><em>Aliquid autem quas cum tempora tempore. Rem quidem nostrum facilis iure ex. Velit fuga reiciendis dolores in est. Ut dolores esse quis ullam. Illo vel tempora esse dolor unde cumque.</em></p>',
        slug: 'amet-sit-commodi-et-inventore-doloremque-velit',
        picture: 'https://picsum.photos/id/70/1000/1000.jpg',
        status: 1,
        created_at: '2023-03-11T20:28:39+00:00',
        updated_at: '2022-03-24T22:19:42+00:00',
        author: {
          id: 4,
          email: 'maya.jenkins@yahoo.com',
          roles: ['ROLE_AUTHOR', 'ROLE_USER'],
          firstname: 'Elfrieda',
          lastname: 'Larkin',
          nickname: 'queenie29',
          code: '#3677',
          avatar:
            'https://back-apotheose.eco-friendly.fr/assets/img/avatars/renard.png',
          is_active: false,
          is_verified: true,
          created_at: '2022-06-10T19:10:30+00:00',
          updated_at: '2022-09-19T21:44:52+00:00',
        },
        category: {
          id: 3,
          name: 'Santé',
          tagline:
            'Dolores corporis ullam libero exercitationem corporis adipisci quo et.',
          slug: 'sante',
        },
      },
      {
        id: 62,
        title: 'Rerum earum nam fugit iure ipsum.',
        content:
          '<p><em>In nobis nam repellendus alias officiis laboriosam. Cum corporis enim quam. Explicabo sint molestiae et qui. Corporis odit et hic laboriosam ut fuga placeat. Ipsam odit totam iusto ducimus molestias.</em></p><h3>Doloribus earum dolores deleniti doloremque.</h3><p>Ipsa et quae accusantium ea. Occaecati reprehenderit sit dicta non eligendi. Et asperiores harum aut est nam. Fuga tempore exercitationem quam velit sit. Voluptatem ut aut similique et optio. Vitae autem aliquam ullam.</p><p><b>Cum facilis est dolorum reiciendis labore voluptates totam accusantium. Sed voluptatem voluptatem cupiditate laudantium dolorum tempore. Distinctio officiis eaque rerum eveniet in laboriosam esse. Nesciunt velit ea officiis aut unde. Aliquid quas recusandae cupiditate dicta aut molestiae sed.</b></p><p>Non vero laudantium accusamus animi similique iusto. Et in neque accusamus dolor tempore. Ex enim quia optio quia. Eum molestiae commodi sunt magnam eveniet molestias nobis. Ex consectetur laborum voluptatem accusantium quidem aut vel.</p><h4>Rerum eveniet rerum dolorum.</h4><ul><li>Placeat omnis ut voluptatem quo.</li><li>Sunt est omnis commodi unde aut non.</li><li>Aut ut dolores neque quo eius cum beatae.</li></ul><h3>Ut in tempore adipisci vitae ad.</h3><p>Cupiditate nihil voluptatem enim. Fugiat itaque nisi accusamus labore voluptatibus numquam beatae. Nemo est quasi in autem et. Assumenda minima nesciunt occaecati.</p><p>Quam ut cumque eos consectetur ipsa ex nulla. Quo quis qui laborum qui mollitia et excepturi. Mollitia facere numquam pariatur et ab exercitationem praesentium. Nulla dolorem voluptas occaecati. Numquam iusto ut possimus laboriosam. Dolorem similique sunt eius totam sint ut.</p><p>Et autem quod magnam ut. Quisquam in ut occaecati deleniti ex et voluptates vel. Quia eos optio omnis enim. Sequi repellat animi rerum at. Voluptatibus corporis eos nemo sed. Nesciunt laborum accusamus est. Aperiam blanditiis officiis enim.</p><p><em>Iure ea atque non eum porro et beatae. Omnis vel mollitia et maxime nam. Earum modi et laudantium facilis. Voluptate laborum maxime libero culpa dicta voluptate odit. Magni quia quaerat sed voluptatibus impedit dolores. Nesciunt velit aut aperiam nesciunt dolore quam. Magni ipsam in aut qui dignissimos. Pariatur ducimus omnis ab perferendis autem.</em></p>',
        slug: 'rerum-earum-nam-fugit-iure-ipsum',
        picture: 'https://picsum.photos/id/57/1000/1000.jpg',
        status: 1,
        created_at: '2023-03-10T00:44:53+00:00',
        updated_at: '2022-12-07T04:55:33+00:00',
        author: {
          id: 9,
          email: 'sienna16@langworth.com',
          roles: ['ROLE_AUTHOR', 'ROLE_USER'],
          firstname: 'Leo',
          lastname: 'Lemke',
          nickname: 'lura09',
          code: '#5351',
          avatar:
            'https://back-apotheose.eco-friendly.fr/assets/img/avatars/ours.png',
          is_active: false,
          is_verified: true,
          created_at: '2022-08-06T08:42:39+00:00',
          updated_at: '2022-12-10T21:10:29+00:00',
        },
        category: {
          id: 1,
          name: 'Mobilité',
          tagline: 'Eaque enim enim quaerat est velit qui quia.',
          slug: 'mobilite',
        },
      },
      {
        id: 93,
        title: 'Libero veritatis eos ex nulla aspernatur est cumque enim.',
        content:
          '<p><em>Ratione officiis molestiae qui placeat aliquam rerum deserunt excepturi. Repudiandae odio qui vitae laboriosam. Et minus asperiores aliquid architecto qui quidem reprehenderit nam. Harum rerum beatae atque at animi. Consequatur fugit qui architecto nulla. Quasi ut quia rerum omnis voluptatem.</em></p><h3>Sed non quam molestiae atque mollitia nesciunt ut.</h3><p>Magni quia voluptatem doloremque dolorem quia. Magnam quae tempore qui iure voluptas mollitia voluptatibus. Voluptatibus laborum at necessitatibus eius pariatur error eius. Magnam nobis sit ut et reiciendis. Beatae cupiditate labore enim similique provident. Totam placeat iusto ut ut.</p><p><b>Nostrum voluptatum omnis id earum eos. Voluptatem est sed quisquam delectus unde temporibus. Autem et delectus ad consequatur voluptatem eius voluptas aut. Eligendi fugit consectetur labore sapiente molestiae quam. Ut repudiandae eum quibusdam dolor molestiae in aut.</b></p><p>Sunt repellat dolores beatae sed magni rem voluptas. Laboriosam numquam est corporis maiores natus ipsa vel. Aut et numquam sint. Provident molestiae quis dolore illum. Aut et vel libero unde quia. Libero voluptatem eos ut ut doloribus. Ut quo odio possimus aut.</p><h4>Quos quibusdam aut adipisci iure tempora cumque non.</h4><ul><li>Dicta beatae vitae adipisci nihil sit.</li><li>Itaque ex et natus facere.</li><li>Praesentium pariatur nam tenetur reprehenderit sed quae et sed.</li></ul><h3>Molestiae sint repudiandae impedit accusamus ut laboriosam.</h3><p>Placeat aliquam praesentium accusamus inventore ut iusto. Aut vitae quam ut voluptas. Rerum accusamus modi est praesentium delectus. Qui incidunt suscipit repellendus. A vel omnis incidunt officia commodi est veniam aperiam. Expedita in et enim deserunt est voluptate. Veniam illo dolore est beatae quia voluptatem magnam. Consectetur ipsam sapiente eius expedita et quia ut. Blanditiis at temporibus fugit est iusto temporibus.</p><p>Omnis adipisci quaerat qui illum iure. Maxime nulla consectetur ipsum tempore necessitatibus deserunt autem. Praesentium adipisci blanditiis aperiam. Veniam ipsam a doloribus non tempore fugiat. At aut doloremque dolorum ex.</p><p>Autem aut laboriosam est quisquam. Eius illo sit sed atque sed. Accusantium numquam reiciendis repellat porro cupiditate voluptatibus reprehenderit quia. Incidunt voluptatem non incidunt architecto. Reiciendis aliquid quia quasi at quia facere voluptas. Modi dicta quos sint est dolore. Omnis ea sit alias ut commodi nobis explicabo. Itaque magni voluptatum ut consequuntur aliquam. Nisi quo consequatur ratione blanditiis architecto.</p><p><em>Repudiandae magni dolor aut iste ut ipsa eligendi. Atque est cupiditate assumenda ducimus aut non quas. Id placeat ut dolorem blanditiis ut aut ut. Soluta ullam omnis deserunt est. Aliquid voluptate quisquam sunt et eaque. Assumenda consequuntur dolorem provident quis voluptate tempora incidunt consequuntur. Optio sit et aliquam aliquid et commodi nesciunt.</em></p>',
        slug: 'libero-veritatis-eos-ex-nulla-aspernatur-est-cumque-enim',
        picture: 'https://picsum.photos/id/171/1000/1000.jpg',
        status: 1,
        created_at: '2023-03-02T20:20:02+00:00',
        updated_at: '2023-02-22T01:46:08+00:00',
        author: {
          id: 2,
          email: 'author@author.com',
          roles: ['ROLE_AUTHOR', 'ROLE_USER'],
          firstname: 'Milan',
          lastname: 'Kundera',
          nickname: 'MilKu',
          code: '#1908',
          avatar:
            'https://back-apotheose.eco-friendly.fr/uploads/users/3-6403a58bd869d.jpg',
          is_active: true,
          is_verified: true,
          created_at: '2022-08-31T04:49:21+00:00',
          updated_at: '2022-10-19T17:07:15+00:00',
        },
        category: {
          id: 1,
          name: 'Mobilité',
          tagline: 'Eaque enim enim quaerat est velit qui quia.',
          slug: 'mobilite',
        },
      },
      {
        id: 95,
        title: 'Et tenetur magni aut minus magni non.',
        content:
          '<p><em>Autem aut et unde perferendis. Earum cupiditate qui aut delectus eligendi. Et quis omnis minima recusandae. Culpa aliquid officia rem quo quo a amet veniam. Enim eum totam unde debitis.</em></p><h3>Reprehenderit quisquam explicabo asperiores est.</h3><p>Aliquam assumenda quia quos et id et culpa. Quia ut qui voluptates asperiores repellendus est consequatur quis. Qui fuga ratione quisquam odio illo quia qui. Non qui pariatur officiis esse voluptatem sit perferendis. Ut nulla sint inventore vitae ipsam.</p><p><b>Molestiae tenetur est explicabo et voluptates voluptates. Doloremque qui aut doloribus beatae nisi cumque dicta. Perspiciatis incidunt totam nihil nisi rem eum. Nemo est ea ad. Veniam iure deserunt officia officiis. Ex ducimus sunt ut rerum architecto mollitia ea quaerat. Porro autem sint doloremque corporis.</b></p><p>Tempore repudiandae optio iusto ratione sit quibusdam. Neque quia at dolorem aperiam. Non corrupti reprehenderit consequatur ad iure ut voluptas. Vero tenetur eos et voluptatem. Fuga cupiditate esse saepe repellendus enim aut iste. Quia omnis iusto itaque est illum illo. Aliquid quia omnis animi. Dolorem laudantium laborum nesciunt nisi explicabo consequatur accusamus.</p><h4>Omnis et sit quis voluptas rem.</h4><ul><li>Quis delectus molestias labore.</li><li>Enim eaque exercitationem neque quia sequi asperiores id.</li><li>Animi autem voluptatum earum.</li></ul><h3>Perspiciatis sequi minima eaque aut dicta nihil.</h3><p>Quo enim et assumenda delectus dolorum. Quasi dolor tenetur nemo est temporibus et. Est cum rerum qui voluptates et quos omnis beatae. Et et odio neque occaecati. Molestias rerum aliquam vel quia delectus. Quod velit velit tenetur nisi inventore rerum quia itaque. Laudantium adipisci voluptatem quo qui sed.</p><p>Minus eligendi sequi numquam dolorem et. Fugit quod dolore eaque quia officiis distinctio iusto. Harum corrupti porro libero omnis perspiciatis quis in. Et voluptatem culpa in et est.</p><p>Dignissimos totam eos magnam ab aut dolore esse quidem. Sunt odio soluta cumque sunt. Porro numquam iusto sequi adipisci hic. Fugit id beatae aperiam exercitationem ut non hic dolorem. Deserunt ut ut sed deserunt eligendi dolor. Eius tempora reprehenderit temporibus totam voluptatibus omnis.</p><p><em>Nostrum blanditiis exercitationem distinctio et eveniet. Molestias reiciendis voluptas et aliquam hic. Sunt et dolorem praesentium a nam numquam repudiandae. Molestias distinctio veritatis id voluptas. Culpa ut aliquam vero sunt odio voluptatem. Quia dignissimos earum voluptatem temporibus consectetur ut id. Eveniet possimus exercitationem omnis ratione ipsam.</em></p>',
        slug: 'et-tenetur-magni-aut-minus-magni-non',
        picture: 'https://picsum.photos/id/76/1000/1000.jpg',
        status: 1,
        created_at: '2023-02-21T10:27:23+00:00',
        updated_at: '2023-01-16T14:18:41+00:00',
        author: {
          id: 9,
          email: 'sienna16@langworth.com',
          roles: ['ROLE_AUTHOR', 'ROLE_USER'],
          firstname: 'Leo',
          lastname: 'Lemke',
          nickname: 'lura09',
          code: '#5351',
          avatar:
            'https://back-apotheose.eco-friendly.fr/assets/img/avatars/ours.png',
          is_active: false,
          is_verified: true,
          created_at: '2022-08-06T08:42:39+00:00',
          updated_at: '2022-12-10T21:10:29+00:00',
        },
        category: {
          id: 1,
          name: 'Mobilité',
          tagline: 'Eaque enim enim quaerat est velit qui quia.',
          slug: 'mobilite',
        },
      },
      {
        id: 57,
        title: 'Dignissimos similique non assumenda animi.',
        content:
          '<p><em>Velit qui doloribus quae non dolorem magni accusamus. Rerum fugiat et autem quam debitis praesentium. Quia deserunt excepturi commodi amet. Et aut eaque voluptatem dolor eum. Impedit molestiae aut ut vero sunt velit. Rem praesentium odit corporis.</em></p><h3>Harum sit laudantium error quia omnis.</h3><p>Nobis voluptas repellendus vel exercitationem inventore perferendis. Ea sint optio odit fugiat beatae quibusdam voluptates ut. Quia optio magni est et in debitis. Et rerum iste numquam ad quaerat. Impedit sit praesentium dolores eius.</p><p><b>Illo culpa odio qui quam nesciunt ut. Sint ipsam ut vero officiis qui. Similique nostrum qui vero. Ut eum aut atque dolorem quia eum placeat. Saepe rerum ut maiores numquam dolor est.</b></p><p>Quisquam fugiat reiciendis ut et perferendis dolore eum. Iste voluptatibus totam voluptate consequatur et in. Ducimus odit at reiciendis assumenda ipsa ut inventore. Ea voluptates sunt aliquam qui nihil quos. Voluptatibus tempora est accusantium repellendus. Nesciunt quia voluptatem et et enim. Cupiditate nam aut dolorum. Quo pariatur iusto qui vero assumenda.</p><h4>Sed ea porro temporibus quaerat sed et fugiat.</h4><ul><li>Aut debitis porro reiciendis non.</li><li>Iure atque repellat et officia.</li><li>Velit consequatur soluta quo ipsa pariatur omnis veritatis.</li></ul><h3>Sint quisquam fuga aut.</h3><p>Aperiam velit illo tempora aliquam. Culpa esse ut inventore et. Veritatis quaerat accusantium saepe. Quia suscipit nobis sint laudantium. Eaque occaecati qui deleniti. Deserunt nesciunt voluptates itaque in. Ea aliquid aspernatur ab iste sunt ratione.</p><p>Atque voluptatem voluptatem omnis fugit aut. Distinctio vitae iste est magnam explicabo non. Vero soluta quos non adipisci occaecati qui. Dolore voluptates dolorem aut voluptas fugiat dolor. Dolorem eaque id eum. Molestiae modi laborum quo cupiditate sit. Sit a eveniet corrupti maiores. Ipsum temporibus quis aut magnam temporibus est.</p><p>Nisi rerum ullam illum voluptate quisquam. Non quis et earum est. Ut aperiam ullam blanditiis et enim quod aut. Quia et ex quam accusamus et. Ab aliquam fugiat dolor nam. Impedit sed ea aut nesciunt temporibus et.</p><p><em>Culpa tempora aut deleniti labore similique tempore. Velit reprehenderit rerum et sunt eos magni. Voluptatem ducimus adipisci aut ut et molestiae nulla. Tempora et voluptatem officiis deserunt delectus. Omnis beatae et fuga blanditiis hic qui.</em></p>',
        slug: 'dignissimos-similique-non-assumenda-animi',
        picture: 'https://picsum.photos/id/23/1000/1000.jpg',
        status: 1,
        created_at: '2023-02-12T04:03:31+00:00',
        updated_at: '2022-12-23T09:18:04+00:00',
        author: {
          id: 9,
          email: 'sienna16@langworth.com',
          roles: ['ROLE_AUTHOR', 'ROLE_USER'],
          firstname: 'Leo',
          lastname: 'Lemke',
          nickname: 'lura09',
          code: '#5351',
          avatar:
            'https://back-apotheose.eco-friendly.fr/assets/img/avatars/ours.png',
          is_active: false,
          is_verified: true,
          created_at: '2022-08-06T08:42:39+00:00',
          updated_at: '2022-12-10T21:10:29+00:00',
        },
        category: {
          id: 2,
          name: 'Maison',
          tagline: 'Eveniet quis reiciendis cum.',
          slug: 'maison',
        },
      },
      {
        id: 70,
        title: 'Rerum possimus inventore facere.',
        content:
          '<p><em>Vel at eos facilis sapiente sunt adipisci exercitationem. Doloremque quasi nihil dolorem. Cumque sed dolor ad iusto. Praesentium velit ea delectus at saepe qui expedita. Eveniet qui laborum ipsum occaecati excepturi aut facilis. Fugiat dolorem odio nisi aut voluptas dolores distinctio.</em></p><h3>Nobis at cupiditate eos voluptatibus.</h3><p>Aliquam natus occaecati explicabo saepe doloribus quibusdam est. Esse animi ut ut aut sunt omnis. Fugit modi rerum eum incidunt consequatur. Aut sint harum sapiente dolor. Quia consectetur unde ipsam sapiente amet.</p><p><b>Nostrum laboriosam est est minus ea voluptatem numquam. Dolorem voluptatem exercitationem veritatis odit. Delectus id esse eaque rerum velit molestiae explicabo voluptates. Odit sunt vel eum quis dolore eligendi. Quibusdam inventore pariatur fuga dolores eaque amet. Quae cum dignissimos est rerum. Corrupti repellat quas dolorem consectetur. Consequuntur id aut asperiores quidem ut cupiditate voluptatum.</b></p><p>Facilis quo et possimus eum dolores necessitatibus. Molestias dignissimos rerum quisquam illum. Nostrum facere enim aspernatur dolorem vel et. Tempora ipsam minus velit. Eos libero velit magni nemo dolores. Voluptates repellendus earum asperiores dolorem quos deleniti voluptas. Aut incidunt eveniet vel voluptatem atque eaque.</p><h4>Blanditiis atque debitis et.</h4><ul><li>Odit minus et totam repudiandae.</li><li>Vero omnis dolor explicabo necessitatibus.</li><li>Dolorum est ullam eligendi non voluptates reiciendis et.</li></ul><h3>Facere culpa ut accusamus necessitatibus ipsam ut vel blanditiis.</h3><p>Veritatis ullam dolor accusamus molestiae. Modi similique voluptas facilis nam. Omnis qui dolor ut similique eum deleniti et minima. Est quasi quibusdam ea eligendi quis et quidem dolores.</p><p>Quidem inventore ratione officiis fuga corrupti in perferendis. Non culpa placeat iusto minima. Amet aliquam sed sapiente dignissimos alias optio magni. Placeat totam ex velit. Doloremque eum placeat et quia dignissimos voluptate optio pariatur.</p><p>Unde rerum veniam tempore non ut exercitationem impedit. Amet eligendi et modi eum aut tenetur nihil. Itaque cupiditate laborum dolorum doloremque temporibus. Qui deserunt consequuntur voluptatem cupiditate facere eligendi. Vel excepturi consequatur similique necessitatibus placeat temporibus quis. Ipsum dolorem et deserunt ut itaque quos aspernatur.</p><p><em>Possimus delectus voluptatem nihil sint quo. Perspiciatis in quibusdam voluptas ea labore ut quae. Molestias et aut iure id quasi dolores dolor. Sit voluptate similique qui aut.</em></p>',
        slug: 'rerum-possimus-inventore-facere',
        picture: 'https://picsum.photos/id/172/1000/1000.jpg',
        status: 1,
        created_at: '2023-02-08T06:10:17+00:00',
        updated_at: '2022-12-19T22:16:34+00:00',
        author: {
          id: 4,
          email: 'maya.jenkins@yahoo.com',
          roles: ['ROLE_AUTHOR', 'ROLE_USER'],
          firstname: 'Elfrieda',
          lastname: 'Larkin',
          nickname: 'queenie29',
          code: '#3677',
          avatar:
            'https://back-apotheose.eco-friendly.fr/assets/img/avatars/renard.png',
          is_active: false,
          is_verified: true,
          created_at: '2022-06-10T19:10:30+00:00',
          updated_at: '2022-09-19T21:44:52+00:00',
        },
        category: {
          id: 3,
          name: 'Santé',
          tagline:
            'Dolores corporis ullam libero exercitationem corporis adipisci quo et.',
          slug: 'sante',
        },
      },
    ],
  },
  advices: {
    home: [
      {
        id: 134,
        title: 'Tenetur est suscipit quam aut qui similique.',
        content:
          '<p>Tempora molestias et consectetur qui voluptatem incidunt. Fuga enim vel distinctio sit architecto voluptatem. Et quas eligendi ut non. Vitae ut reiciendis dolore quidem distinctio. Placeat occaecati corrupti rerum officiis error magnam animi aut. Dolore qui impedit esse similique voluptas excepturi. Nisi reiciendis sit corrupti temporibus. Reprehenderit nulla accusamus necessitatibus in qui nisi laboriosam quaerat.</p><p>Aut aut asperiores blanditiis non. Qui aut eos velit quaerat qui quo. Nihil sit ipsum nemo. Veniam voluptate consequatur velit in nulla quia. Et occaecati repellat aliquam error voluptas voluptas qui. Dolorem vero tempora sit laboriosam at voluptatum autem. Doloribus amet deleniti eaque accusamus quaerat perferendis exercitationem. Quia est quod rerum inventore nam beatae.</p><p>Pariatur aspernatur beatae natus nam. A nihil labore atque porro aut. Doloremque reiciendis omnis ad ut. Odit quo temporibus sed quis odio sint excepturi sunt. Voluptatem sequi possimus qui et.</p>',
        slug: 'tenetur-est-suscipit-quam-aut-qui-similique',
        status: 1,
        created_at: '2023-03-12T21:03:44+00:00',
        updated_at: '2022-08-29T02:06:35+00:00',
        contributor: {
          id: 3,
          email: 'user@user.com',
          roles: ['ROLE_USER'],
          firstname: 'Jeff',
          lastname: 'Lebowski',
          nickname: 'The_Dude',
          code: '#2576',
          avatar:
            'https://back-apotheose.eco-friendly.fr/assets/img/avatars/ours.png',
          is_active: true,
          is_verified: true,
          created_at: '2023-03-11T17:52:55+00:00',
          updated_at: '2023-03-13T08:36:53+00:00',
        },
        category: {
          id: 3,
          name: 'Santé',
          tagline:
            'Dolores corporis ullam libero exercitationem corporis adipisci quo et.',
          slug: 'sante',
        },
      },
      {
        id: 76,
        title: 'Dolorem ut cupiditate et quisquam et aut libero.',
        content:
          '<p>Commodi reiciendis dolore ut quasi illo. Facere eum quibusdam qui officia architecto quibusdam. Vel id et quia sit ut. Consequatur voluptas quam autem dolores quia ut nesciunt dignissimos. Commodi soluta nihil iusto. Facilis architecto nesciunt et suscipit cupiditate laudantium.</p><p>Perspiciatis sint eaque ipsa aliquid consequatur. Fugit doloribus a qui ut beatae id. Ut pariatur culpa modi quis. Laboriosam ipsum natus cumque dolore. Vel minima ipsum soluta illo consequuntur. Perspiciatis labore harum iste voluptas adipisci dolor. Ratione magni dolorem ipsa porro.</p><p>Et a cupiditate est et iure sunt. Beatae rerum ipsam voluptas quidem. Doloribus rerum eius dolorum illo maiores odit sit id. Aperiam rerum sed debitis et. Voluptatem incidunt iure omnis in odio fugit. Dolor voluptate distinctio expedita optio. Soluta voluptatem amet ea iure dolore quas.</p>',
        slug: 'dolorem-ut-cupiditate-et-quisquam-et-aut-libero',
        status: 1,
        created_at: '2023-03-11T14:17:38+00:00',
        updated_at: '2023-01-15T06:17:22+00:00',
        contributor: {
          id: 19,
          email: 'yasmine.will@barrows.com',
          roles: ['ROLE_USER'],
          firstname: 'Francesca',
          lastname: 'Quitzon',
          nickname: 'znitzsche',
          code: '#7543',
          avatar:
            'https://back-apotheose.eco-friendly.fr/assets/img/avatars/grenouille.png',
          is_active: true,
          is_verified: true,
          created_at: '2022-06-10T09:53:51+00:00',
          updated_at: '2022-08-03T17:15:54+00:00',
        },
        category: {
          id: 3,
          name: 'Santé',
          tagline:
            'Dolores corporis ullam libero exercitationem corporis adipisci quo et.',
          slug: 'sante',
        },
      },
      {
        id: 69,
        title: 'Et illum mollitia qui qui occaecati aut nobis.',
        content:
          '<p>Illo ut incidunt quia ex. Quasi voluptatem corrupti nostrum earum aut. Dignissimos non similique et porro. Voluptas maxime nisi corporis sint consequuntur officiis. Iusto voluptas laborum dicta sit rem ipsum. Sit autem dolorem in tempore repudiandae ab ipsam officiis. Rerum dolor et eligendi temporibus atque. Magnam a reprehenderit debitis molestias.</p><p>Sint id in aut omnis. Debitis corrupti voluptas et est sint temporibus et. Sint ipsam repudiandae corporis et. Nesciunt repudiandae consequatur optio neque. Soluta aut ut veniam vero quisquam aliquam tempore occaecati. Ipsam in eum et dolor. Laudantium nulla provident sit rerum. Aut esse sed maxime voluptatem id.</p><p>Et iste perferendis cupiditate commodi consequuntur et. Iste ullam eius dolores tenetur perspiciatis. Repellat consequatur mollitia accusantium incidunt qui. Minus molestiae eveniet aperiam labore velit cum. Autem accusamus aperiam dolor nulla sit est placeat. Quae quae quibusdam nobis asperiores et. Quo est iste reiciendis eum. Debitis sunt ipsa culpa dolore expedita. Qui et consequatur animi dignissimos quia quia aut distinctio.</p>',
        slug: 'et-illum-mollitia-qui-qui-occaecati-aut-nobis',
        status: 1,
        created_at: '2023-03-05T13:44:42+00:00',
        updated_at: '2022-07-03T07:38:47+00:00',
        contributor: {
          id: 39,
          email: 'gerry32@rogahn.com',
          roles: ['ROLE_USER'],
          firstname: 'Gene',
          lastname: 'Lemke',
          nickname: 'gaylord.webster',
          code: '#4186',
          avatar:
            'https://back-apotheose.eco-friendly.fr/assets/img/avatars/renard.png',
          is_active: true,
          is_verified: true,
          created_at: '2023-01-18T20:32:06+00:00',
          updated_at: '2022-07-17T14:42:38+00:00',
        },
        category: {
          id: 4,
          name: 'Energie',
          tagline: 'Nisi modi ducimus laborum autem.',
          slug: 'energie',
        },
      },
      {
        id: 129,
        title: 'Totam aut aut aliquam commodi et.',
        content:
          '<p>Sit reiciendis vero et magni mollitia ut et. Unde voluptatem ut qui laudantium officiis iure. Nesciunt alias expedita aliquam reprehenderit. Consequuntur molestias ut quidem molestiae. Nemo ratione mollitia ipsa architecto et deserunt omnis totam. Occaecati deserunt non vero consectetur sed aut aut. Velit corporis dignissimos dolore deleniti molestias aperiam. Autem sequi illo voluptatum saepe et qui voluptatum. Et necessitatibus excepturi qui id quo natus.</p><p>Perspiciatis aut autem commodi minus. Consequatur esse animi vel sunt cum qui. Veritatis quidem sed voluptatem in voluptas fugiat molestiae. Velit voluptatem voluptas iure est.</p><p>Voluptates et rem quas et deserunt dolor cumque. Veritatis tempore non nihil nisi quisquam. Qui vero aliquid ipsa est. Deleniti unde numquam dolorem voluptatum voluptatem. Aperiam atque perspiciatis vel rem enim. Libero voluptate voluptatem quis sunt quidem repellendus. Veniam et quia dolorem ut consequatur in rem accusamus. Repellat labore asperiores laborum officia.</p>',
        slug: 'totam-aut-aut-aliquam-commodi-et',
        status: 1,
        created_at: '2023-02-22T04:13:15+00:00',
        updated_at: '2022-08-07T06:30:23+00:00',
        contributor: {
          id: 40,
          email: 'lilyan65@gmail.com',
          roles: ['ROLE_USER'],
          firstname: 'Archibald',
          lastname: 'Larkin',
          nickname: 'marquise18',
          code: '#4050',
          avatar:
            'https://back-apotheose.eco-friendly.fr/assets/img/avatars/grenouille.png',
          is_active: true,
          is_verified: true,
          created_at: '2022-04-23T06:15:08+00:00',
          updated_at: '2023-01-18T21:35:15+00:00',
        },
        category: {
          id: 4,
          name: 'Energie',
          tagline: 'Nisi modi ducimus laborum autem.',
          slug: 'energie',
        },
      },
      {
        id: 118,
        title: 'Ut autem odio minus aperiam.',
        content:
          '<p>Quasi debitis reiciendis voluptatem consequatur facilis minima corrupti. At odit soluta sit numquam minus hic. Recusandae ut aut est. Numquam laborum dolorem quo. Quibusdam dolores fugiat illo molestiae consequatur. Illo consequuntur repellat enim. Ut delectus sint eum.</p><p>Ut iusto sit ab debitis est totam. Autem laudantium sed voluptas ab consequatur commodi dolor. Dolores ad quia quisquam quidem sed dolores iste quia. Est cupiditate atque debitis. Iusto asperiores veritatis aut necessitatibus. Fugit nobis nihil expedita rerum reprehenderit quasi. Quis dolor tempore est quae. Sed eveniet nobis hic ut omnis minima nihil voluptatem.</p><p>Aut consequatur non omnis vitae est. Sit aut qui dolor amet aspernatur eveniet earum. Nihil qui suscipit odio dolorem. Id rerum occaecati et. Ut eligendi perferendis sit corrupti eligendi ducimus voluptas. Quod ea qui officiis quisquam dolore. Unde doloremque et recusandae. Id sunt perferendis consequuntur cumque sed nisi debitis.</p>',
        slug: 'ut-autem-odio-minus-aperiam',
        status: 1,
        created_at: '2023-02-10T02:40:12+00:00',
        updated_at: '2022-11-17T11:10:06+00:00',
        contributor: {
          id: 25,
          email: 'kennith15@hotmail.com',
          roles: ['ROLE_USER'],
          firstname: 'Hannah',
          lastname: 'Homenick',
          nickname: 'bosco.dedrick',
          code: '#2904',
          avatar:
            'https://back-apotheose.eco-friendly.fr/assets/img/avatars/lievre.png',
          is_active: true,
          is_verified: true,
          created_at: '2023-02-24T19:23:39+00:00',
          updated_at: '2022-10-06T00:33:21+00:00',
        },
        category: {
          id: 1,
          name: 'Mobilité',
          tagline: 'Eaque enim enim quaerat est velit qui quia.',
          slug: 'mobilite',
        },
      },
      {
        id: 132,
        title: 'Dolorum unde animi ea sunt placeat in.',
        content:
          '<p>Voluptatem qui qui blanditiis similique perspiciatis consequuntur sed. A unde non dolores aut et magnam delectus. Et est in voluptas quod explicabo deleniti. Animi quo aut molestias ipsum labore excepturi. Quia reprehenderit cum soluta officiis voluptas minus.</p><p>Illo aliquid voluptatem enim sunt quis dolor. Quam dolore vel velit atque temporibus non officia. Maiores enim velit et quia repellendus consequatur recusandae dolorem. Magni quo et dolorum ipsam. Dolores hic qui cupiditate et.</p><p>Unde dignissimos ut dignissimos. Quae consequatur rerum accusamus sint rerum consequuntur. Est excepturi voluptas perferendis perferendis. Enim aliquam dolor illo quis voluptatem sapiente. Consequuntur saepe rerum velit et aut corporis. Perspiciatis dolorum ipsam laudantium. Sit suscipit quas hic. Ea accusantium aliquam et repudiandae.</p>',
        slug: 'dolorum-unde-animi-ea-sunt-placeat-in',
        status: 1,
        created_at: '2023-02-09T11:07:12+00:00',
        updated_at: '2022-10-01T20:03:11+00:00',
        contributor: {
          id: 45,
          email: 'feest.brad@hotmail.com',
          roles: ['ROLE_USER'],
          firstname: 'Jalyn',
          lastname: 'Kautzer',
          nickname: 'cornelius86',
          code: '#5259',
          avatar:
            'https://back-apotheose.eco-friendly.fr/assets/img/avatars/ours.png',
          is_active: true,
          is_verified: true,
          created_at: '2022-08-12T21:22:06+00:00',
          updated_at: '2022-08-24T17:11:11+00:00',
        },
        category: {
          id: 4,
          name: 'Energie',
          tagline: 'Nisi modi ducimus laborum autem.',
          slug: 'energie',
        },
      },
      {
        id: 87,
        title: 'Consequuntur autem delectus aspernatur aspernatur et non.',
        content:
          '<p>Harum voluptate sint doloribus eligendi eos. Soluta voluptatum est animi amet voluptatem qui a. Ut beatae sit saepe soluta omnis voluptates. Quam dolore tenetur velit qui et dolorum et. Nulla rerum ut porro. Est qui sed dolorem incidunt.</p><p>Dolorem iusto odio qui itaque aperiam. Molestiae quas mollitia beatae est aut quibusdam sit voluptatem. Porro aut ut corporis rem. Enim amet exercitationem omnis aperiam ipsam. Cum deserunt mollitia reprehenderit cupiditate. Temporibus quis eligendi et qui dolore ut nemo. Ea quas et dolorem molestias aperiam perferendis dolores iusto. Vel omnis esse quisquam sequi et ex. Sit rerum occaecati odio quia atque et.</p><p>Distinctio dolor ut asperiores et illum dolore accusamus. Iste ex quas natus totam explicabo. Sed beatae vel neque consequatur. Distinctio rerum fugiat est necessitatibus tempore non aut. Est molestiae quisquam consectetur reprehenderit excepturi vel eos. Eligendi velit reprehenderit laudantium. Velit cupiditate impedit sunt ab ullam.</p>',
        slug: 'consequuntur-autem-delectus-aspernatur-aspernatur-et-non',
        status: 1,
        created_at: '2023-02-04T14:20:58+00:00',
        updated_at: '2023-01-11T13:23:33+00:00',
        contributor: {
          id: 22,
          email: 'ogrimes@hotmail.com',
          roles: ['ROLE_USER'],
          firstname: 'Braeden',
          lastname: 'Streich',
          nickname: 'pboyer',
          code: '#1094',
          avatar:
            'https://back-apotheose.eco-friendly.fr/assets/img/avatars/chevreuil.png',
          is_active: true,
          is_verified: true,
          created_at: '2022-08-30T15:09:31+00:00',
          updated_at: '2022-05-23T04:37:31+00:00',
        },
        category: {
          id: 3,
          name: 'Santé',
          tagline:
            'Dolores corporis ullam libero exercitationem corporis adipisci quo et.',
          slug: 'sante',
        },
      },
      {
        id: 140,
        title: 'A adipisci quis similique et.',
        content:
          '<p>Atque eum nam quis optio sunt est dolor. Id et et autem laudantium. Reprehenderit voluptate quis exercitationem mollitia dolores alias autem. Quos animi facere culpa magnam fugiat illo rem excepturi. Quidem repudiandae voluptates architecto. Quos sunt et inventore sequi. Debitis numquam deleniti vitae est laboriosam omnis. Pariatur eos enim reprehenderit quae.</p><p>Eius qui odit cupiditate sed. Sunt aut et voluptate qui omnis ipsum. Dolores enim alias aliquam et qui. Qui reiciendis rem nesciunt aperiam ut eveniet. Recusandae omnis occaecati delectus ducimus.</p><p>Quia perferendis perspiciatis modi fugiat. Ullam accusantium deserunt doloremque quae est. Ratione cumque laboriosam et deserunt dolor eos rerum. Voluptate odio molestias provident facilis et. Quibusdam qui quibusdam quaerat voluptates quae vel. Rem officiis facere numquam voluptatem nesciunt voluptate. Architecto consequuntur eos laudantium nobis dolores quisquam et et. Repellat molestias animi enim. Deserunt totam odio labore qui.</p>',
        slug: 'a-adipisci-quis-similique-et',
        status: 1,
        created_at: '2023-01-29T08:21:29+00:00',
        updated_at: '2022-06-08T10:29:55+00:00',
        contributor: {
          id: 43,
          email: 'sbechtelar@bins.biz',
          roles: ['ROLE_USER'],
          firstname: 'Selmer',
          lastname: 'Schulist',
          nickname: 'krystal82',
          code: '#1011',
          avatar:
            'https://back-apotheose.eco-friendly.fr/assets/img/avatars/chevreuil.png',
          is_active: true,
          is_verified: true,
          created_at: '2022-10-28T13:15:38+00:00',
          updated_at: '2022-06-15T12:41:05+00:00',
        },
        category: {
          id: 4,
          name: 'Energie',
          tagline: 'Nisi modi ducimus laborum autem.',
          slug: 'energie',
        },
      },
    ],
  },
};
